services:
  backend:
    build:
      context: cend-backend
      target: builder
    volumes:
      - cend-db:/cend-db
    ports:
      - "8080:8080"
    env_file:
      - backend.env
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  cend-db: